trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**\*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  framework: 'netstandard2.0'
  projectName: 'DevFromDownUnder.Gs1BarcodeParser'
  releaseProject: '$(Build.SourcesDirectory)\src\$(projectName)\$(projectName).csproj'
  releaseType: '-preview'
  timestamp: $[format('{0:yyyyMMddHHmmss}', pipeline.startTime)]

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\src\$(projectName)\bin\$(buildConfiguration)\$(framework)\'
    Contents: '*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\nuget'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\pipelines\'
    Contents: 'DevFromDownUnder.nuspec'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\nuget'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\'
    Contents: 'readme.md'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\nuget'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\images\'
    Contents: 'icon.jpg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\nuget'

- task: ExecutableInfoReader@1
  inputs:
    fileName: '$(Build.ArtifactStagingDirectory)\nuget\$(projectName).dll'
    variableRoot: '$(projectName)'
    loadProductVersion: false
    loadAssemblyVersion: true

- task: SimpleNuspecVersionSetter@1
  inputs:
    RootDirectory: '$(Build.ArtifactStagingDirectory)'
    NewVersion: '$(packageVersion)'

- task: VariableSetTask@1
  inputs:
    VariableName: 'packageVersion'
    Value: '$($(projectName).AssemblyVersionInfo.Version)$(releaseType)-$(timestamp)'
    IsSecret: false

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '$(Build.ArtifactStagingDirectory)\nuget\DevFromDownUnder.nuspec'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'packageVersion'
    basePath: '$(Build.ArtifactStagingDirectory)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)\*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(projectName)/$(projectName)-nuget$(releaseType)'

- task: DotNetCoreCLI@2
  displayName: Nuget.org api key workaround
  inputs:
    command: custom
    custom: nuget
    arguments: >
      push $(Build.ArtifactStagingDirectory)\*.nupkg
      -s https://api.nuget.org/v3/index.json
      -k $(NugetPAT)