using DevFromDownUnder.Gs1BarcodeParser.Barcode.Definition.AI.Enums;
using System.Collections.Generic;

namespace DevFromDownUnder.Gs1BarcodeParser.Barcode.Definition.AI
{
    public static class AIMetadata
    {
        private static readonly Dictionary<AITypes, string> Titles = new Dictionary<AITypes, string>()
        {
                { AITypes.Unknown, "UNKNOWN" },
                { AITypes.Sscc, "SSCC" },
                { AITypes.Gtin, "GTIN" },
                { AITypes.Content, "CONTENT" },
                { AITypes.MtoGtin, "MTO GTIN" },
                { AITypes.BatchLot, "BATCH/LOT" },
                { AITypes.ProdDate, "PROD DATE" },
                { AITypes.DueDate, "DUE DATE" },
                { AITypes.PackDate, "PACK DATE" },
                { AITypes.BestBeforeOrBestBy, "BEST BEFORE or BEST BY" },
                { AITypes.SellBy, "SELL BY" },
                { AITypes.UseByOrExpiry, "USE BY or EXPIRY" },
                { AITypes.Variant, "VARIANT" },
                { AITypes.Cpv, "CPV" },
                { AITypes.Tpx, "TPX" },
                { AITypes.AdditionalId, "ADDITIONAL ID" },
                { AITypes.CustPartNo, "CUST. PART No." },
                { AITypes.MtoVariant, "MTO VARIANT" },
                { AITypes.Pcn, "PCN" },
                { AITypes.SecondarySerial, "SECONDARY SERIAL" },
                { AITypes.RefToSource, "REF. TO SOURCE" },
                { AITypes.Gdti, "GDTI" },
                { AITypes.GlnExtensionComponent, "GLN EXTENSION COMPONENT" },
                { AITypes.Gcn, "GCN" },
                { AITypes.VarCount, "VAR. COUNT" },
                { AITypes.NetWeightKg, "NET WEIGHT (kg)" },
                { AITypes.LengthM, "LENGTH (m)" },
                { AITypes.WidthM, "WIDTH (m)" },
                { AITypes.HeightM, "HEIGHT (m)" },
                { AITypes.AreaM2, "AREA (m²)" },
                { AITypes.NetVolumeL, "NET VOLUME (l)" },
                { AITypes.NetVolumeM3, "NET VOLUME (m³)" },
                { AITypes.NetWeightLb, "NET WEIGHT (lb)" },
                { AITypes.LengthIn, "LENGTH (in)" },
                { AITypes.LengthFt, "LENGTH (ft)" },
                { AITypes.LengthYd, "LENGTH (yd)" },
                { AITypes.WidthIn, "WIDTH (in)" },
                { AITypes.WidthFt, "WIDTH (ft)" },
                { AITypes.WidthYd, "WIDTH (yd)" },
                { AITypes.HeightIn, "HEIGHT (in)" },
                { AITypes.HeightFt, "HEIGHT (ft)" },
                { AITypes.HeightYd, "HEIGHT (yd)" },
                { AITypes.GrossWeightKg, "GROSS WEIGHT (kg)" },
                { AITypes.LengthMLog, "LENGTH (m), log" },
                { AITypes.WidthMLog, "WIDTH (m), log" },
                { AITypes.HeightMLog, "HEIGHT (m), log" },
                { AITypes.AreaM2Log, "AREA (m²), log" },
                { AITypes.VolumeLLog, "VOLUME (l), log" },
                { AITypes.VolumeM3Log, "VOLUME (m³), log" },
                { AITypes.KgPerM2, "KG PER m²" },
                { AITypes.GrossWeightLb, "GROSS WEIGHT (lb)" },
                { AITypes.LengthInLog, "LENGTH (in), log" },
                { AITypes.LengthFtLog, "LENGTH (ft), log" },
                { AITypes.LengthYdLog, "LENGTH (yd), log" },
                { AITypes.WidthInLog, "WIDTH (in), log" },
                { AITypes.WidthFtLog, "WIDTH (ft), log" },
                { AITypes.WidthYdLog, "WIDTH (yd), log" },
                { AITypes.HeightInLog, "HEIGHT (in), log" },
                { AITypes.HeightFtLog, "HEIGHT (ft), log" },
                { AITypes.HeightYdLog, "HEIGHT (yd), log" },
                { AITypes.AreaIn2, "AREA (in²)" },
                { AITypes.AreaFt2, "AREA (ft²)" },
                { AITypes.AreaYd2, "AREA (yd²)" },
                { AITypes.AreaIn2Log, "AREA (in²), log" },
                { AITypes.AreaFt2Log, "AREA (ft²), log" },
                { AITypes.AreaYd2Log, "AREA (yd²), log" },
                { AITypes.NetWeightTOz, "NET WEIGHT (t oz)" },
                { AITypes.NetVolumeOz, "NET VOLUME (oz)" },
                { AITypes.NetVolumeQt, "NET VOLUME (qt)" },
                { AITypes.NetVolumeGal, "NET VOLUME (gal.)" },
                { AITypes.VolumeQtLog, "VOLUME (qt), log" },
                { AITypes.VolumeGalLog, "VOLUME (gal.), log" },
                { AITypes.VolumeIn3, "VOLUME (in³)" },
                { AITypes.VolumeFt3, "VOLUME (ft³)" },
                { AITypes.VolumeYd3, "VOLUME (yd³)" },
                { AITypes.VolumeIn3Log, "VOLUME (in³), log" },
                { AITypes.VolumeFt3Log, "VOLUME (ft³), log" },
                { AITypes.VolumeYd3Log, "VOLUME (yd³), log" },
                { AITypes.Count, "COUNT" },
                { AITypes.Amount, "AMOUNT" },
                { AITypes.AmountWithCode, "AMOUNT" },
                { AITypes.Price, "PRICE" },
                { AITypes.PriceWithCode, "PRICE" },
                { AITypes.PrcntOff, "PRCNT OFF" },
                { AITypes.PricePerUom, "PRICE/UoM" },
                { AITypes.OrderNumber, "ORDER NUMBER" },
                { AITypes.Ginc, "GINC" },
                { AITypes.Gsin, "GSIN" },
                { AITypes.Route, "ROUTE" },
                { AITypes.ShipToLoc, "SHIP TO LOC" },
                { AITypes.BillTo, "BILL TO" },
                { AITypes.PurchaseFrom, "PURCHASE FROM" },
                { AITypes.ShipForLoc, "SHIP FOR LOC" },
                { AITypes.LocNo, "LOC No." },
                { AITypes.PayTo, "PAY TO" },
                { AITypes.ProdServLoc, "PROD/SERV LOC" },
                { AITypes.Party, "PARTY" },
                { AITypes.ShipToPostSimple, "SHIP TO POST" },
                { AITypes.ShipToPostWithCountry, "SHIP TO POST" },
                { AITypes.Origin, "ORIGIN" },
                { AITypes.CountryInitialProcess, "COUNTRY - INITIAL PROCESS" },
                { AITypes.CountryProcess, "COUNTRY - PROCESS" },
                { AITypes.CountryDisassembly, "COUNTRY - DISASSEMBLY" },
                { AITypes.CountryFullProcess, "COUNTRY - FULL PROCESS" },
                { AITypes.OriginSubdivision, "ORIGIN SUBDIVISION" },
                { AITypes.ShipToComp, "SHIP TO COMP" },
                { AITypes.ShipToName, "SHIP TO NAME" },
                { AITypes.ShipToAdd1, "SHIP TO ADD1" },
                { AITypes.ShipToAdd2, "SHIP TO ADD2" },
                { AITypes.ShipToSub, "SHIP TO SUB" },
                { AITypes.ShipToReg, "SHIP TO REG" },
                { AITypes.ShipToCountry, "SHIP TO COUNTRY" },
                { AITypes.ShipToPhone, "SHIP TO PHONE" },
                { AITypes.ShipToGeo, "SHIP TO GEO" },
                { AITypes.RtnToComp, "RTN TO COMP" },
                { AITypes.RtnToName, "RTN TO NAME" },
                { AITypes.RtnToAdd1, "RTN TO ADD1" },
                { AITypes.RtnToAdd2, "RTN TO ADD2" },
                { AITypes.RtnToSub, "RTN TO SUB" },
                { AITypes.RtnToLoc, "RTN TO LOC" },
                { AITypes.RtnToReg, "RTN TO REG" },
                { AITypes.RtnToCountry, "RTN TO COUNTRY" },
                { AITypes.RtnToPost, "RTN TO POST" },
                { AITypes.RtnToPhone, "RTN TO PHONE" },
                { AITypes.SrvDescription, "SRV DESCRIPTION" },
                { AITypes.DangerousGoods, "DANGEROUS GOODS" },
                { AITypes.AuthToLeave, "AUTH TO LEAVE" },
                { AITypes.SigRequired, "SIG REQUIRED" },
                { AITypes.NotBefDelDt, "NOT BEF DEL DT" },
                { AITypes.NotAftDelDt, "NOT AFT DEL DT" },
                { AITypes.RelDate, "REL DATE" },
                { AITypes.MaxTempF, "MAX TEMP F." },
                { AITypes.MaxTempC, "MAX TEMP C." },
                { AITypes.MinTempF, "MIN TEMP F." },
                { AITypes.MinTempC, "MIN TEMP C." },
                { AITypes.Nsn, "NSN" },
                { AITypes.MeatCut, "MEAT CUT" },
                { AITypes.ExpiryTime, "EXPIRY TIME" },
                { AITypes.ActivePotency, "ACTIVE POTENCY" },
                { AITypes.CatchArea, "CATCH AREA" },
                { AITypes.FirstFreezeDate, "FIRST FREEZE DATE" },
                { AITypes.HarvestDate, "HARVEST DATE" },
                { AITypes.AquaticSpecies, "AQUATIC SPECIES" },
                { AITypes.FishingGearType, "FISHING GEAR TYPE" },
                { AITypes.ProdMethod, "PROD METHOD" },
                { AITypes.TestByDate, "TEST BY DATE" },
                { AITypes.RefurbLot, "REFURB LOT" },
                { AITypes.FuncStat, "FUNC STAT" },
                { AITypes.RevStat, "REV STAT" },
                { AITypes.GiaiAssembly, "GIAI - ASSEMBLY" },
                { AITypes.Processor0, "PROCESSOR # 0" },
                { AITypes.Processor1, "PROCESSOR # 1" },
                { AITypes.Processor2, "PROCESSOR # 2" },
                { AITypes.Processor3, "PROCESSOR # 3" },
                { AITypes.Processor4, "PROCESSOR # 4" },
                { AITypes.Processor5, "PROCESSOR # 5" },
                { AITypes.Processor6, "PROCESSOR # 6" },
                { AITypes.Processor7, "PROCESSOR # 7" },
                { AITypes.Processor8, "PROCESSOR # 8" },
                { AITypes.Processor9, "PROCESSOR # 9" },
                { AITypes.UicExt, "UIC+EXT" },
                { AITypes.UfrgtUnitType, "UFRGT UNIT TYPE" },
                { AITypes.NhrnPzn, "NHRN PZN" },
                { AITypes.NhrnCip, "NHRN CIP" },
                { AITypes.NhrnCn, "NHRN CN" },
                { AITypes.NhrnDrn, "NHRN DRN" },
                { AITypes.NhrnAim, "NHRN AIM" },
                { AITypes.NhrnNdc, "NHRN NDC" },
                { AITypes.NhrnAic, "NHRN AIC" },
                { AITypes.Cert1, "CERT # 1" },
                { AITypes.Cert2, "CERT # 2" },
                { AITypes.Cert3, "CERT # 3" },
                { AITypes.Cert4, "CERT # 4" },
                { AITypes.Cert5, "CERT # 5" },
                { AITypes.Cert6, "CERT # 6" },
                { AITypes.Cert7, "CERT # 7" },
                { AITypes.Cert8, "CERT # 8" },
                { AITypes.Cert9, "CERT # 9" },
                { AITypes.Cert10, "CERT # 10" },
                { AITypes.Protocol, "PROTOCOL" },
                { AITypes.AidcMediaType, "AIDC MEDIA TYPE" },
                { AITypes.Vcn, "VCN" },
                { AITypes.Dob, "DOB" },
                { AITypes.DobTime, "DOB TIME" },
                { AITypes.BioSex, "BIO SEX" },
                { AITypes.FamilyName, "FAMILY NAME" },
                { AITypes.GivenName, "GIVEN NAME" },
                { AITypes.Suffix, "SUFFIX" },
                { AITypes.FullName, "FULL NAME" },
                { AITypes.PersonAddr, "PERSON ADDR" },
                { AITypes.BirthSequence, "BIRTH SEQUENCE" },
                { AITypes.Baby, "BABY" },
                { AITypes.Dimensions, "DIMENSIONS" },
                { AITypes.CmtNo, "CMT No." },
                { AITypes.Grai, "GRAI" },
                { AITypes.Giai, "GIAI" },
                { AITypes.PricePerUnit, "PRICE PER UNIT" },
                { AITypes.Itip, "ITIP" },
                { AITypes.Iban, "IBAN" },
                { AITypes.ProdTime, "PROD TIME" },
                { AITypes.Optsen, "OPTSEN" },
                { AITypes.Cpid, "CPID" },
                { AITypes.CpidSerial, "CPID SERIAL" },
                { AITypes.Version, "VERSION" },
                { AITypes.Gmn, "GMN" },
                { AITypes.Mudi, "MUDI" },
                { AITypes.GsrnProvider, "GSRN - PROVIDER" },
                { AITypes.GsrnRecipient, "GSRN - RECIPIENT" },
                { AITypes.Srin, "SRIN" },
                { AITypes.RefNo, "REF No." },
                { AITypes.ItipContent, "ITIP CONTENT" },
                { AITypes.Digsig, "DIGSIG" },
                { AITypes.CouponCode, "COUPON CODE" },
                { AITypes.Points, "POINTS" },
                { AITypes.CouponPosOffer, "COUPON POSITIVE OFFER" },
                { AITypes.ProductUrl, "PRODUCT URL" },
                { AITypes.Internal90, "INTERNAL" },
                { AITypes.Internal91, "INTERNAL" },
                { AITypes.Internal92, "INTERNAL" },
                { AITypes.Internal93, "INTERNAL" },
                { AITypes.Internal94, "INTERNAL" },
                { AITypes.Internal95, "INTERNAL" },
                { AITypes.Internal96, "INTERNAL" },
                { AITypes.Internal97, "INTERNAL" },
                { AITypes.Internal98, "INTERNAL" },
                { AITypes.Internal99, "INTERNAL" }
        };

        public static string GetTitle(AITypes aiType)
        {
            if (Titles.TryGetValue(aiType, out string title))
            {
                return title;
            }
            else
            {
                return string.Empty;
            }
        }
    }
}